---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy warfile to Tomcat
      copy: 
        src: '/var/snap/jenkins/4874/workspace/MyWebApp/target/MyWebApp.war'
        dest: '/opt/tomcat/webapps/MyWebApp.war'
        remote_src: no

